// AUTO-GENERATED by scripts/gen-lists.mjs from the runtime Intl/ICU data.
// Do not edit by hand — re-run the generator to refresh.
// `offsetLabel` is a snapshot from generation time; the stored IANA `value` is
// what's authoritative and stays DST-correct at runtime.

export type Timezone = {
  value: string;
  region: string;
  city: string;
  offsetLabel: string;
  offsetMinutes: number;
};

export const TIMEZONES: Timezone[] = [
  {
    "value": "Pacific/Midway",
    "region": "Pacific",
    "city": "Midway",
    "offsetLabel": "UTC-11:00",
    "offsetMinutes": -660
  },
  {
    "value": "Pacific/Niue",
    "region": "Pacific",
    "city": "Niue",
    "offsetLabel": "UTC-11:00",
    "offsetMinutes": -660
  },
  {
    "value": "Pacific/Pago_Pago",
    "region": "Pacific",
    "city": "Pago Pago",
    "offsetLabel": "UTC-11:00",
    "offsetMinutes": -660
  },
  {
    "value": "Pacific/Honolulu",
    "region": "Pacific",
    "city": "Honolulu",
    "offsetLabel": "UTC-10:00",
    "offsetMinutes": -600
  },
  {
    "value": "Pacific/Rarotonga",
    "region": "Pacific",
    "city": "Rarotonga",
    "offsetLabel": "UTC-10:00",
    "offsetMinutes": -600
  },
  {
    "value": "Pacific/Tahiti",
    "region": "Pacific",
    "city": "Tahiti",
    "offsetLabel": "UTC-10:00",
    "offsetMinutes": -600
  },
  {
    "value": "Pacific/Marquesas",
    "region": "Pacific",
    "city": "Marquesas",
    "offsetLabel": "UTC-09:30",
    "offsetMinutes": -570
  },
  {
    "value": "America/Adak",
    "region": "America",
    "city": "Adak",
    "offsetLabel": "UTC-09:00",
    "offsetMinutes": -540
  },
  {
    "value": "Pacific/Gambier",
    "region": "Pacific",
    "city": "Gambier",
    "offsetLabel": "UTC-09:00",
    "offsetMinutes": -540
  },
  {
    "value": "America/Anchorage",
    "region": "America",
    "city": "Anchorage",
    "offsetLabel": "UTC-08:00",
    "offsetMinutes": -480
  },
  {
    "value": "America/Juneau",
    "region": "America",
    "city": "Juneau",
    "offsetLabel": "UTC-08:00",
    "offsetMinutes": -480
  },
  {
    "value": "America/Metlakatla",
    "region": "America",
    "city": "Metlakatla",
    "offsetLabel": "UTC-08:00",
    "offsetMinutes": -480
  },
  {
    "value": "America/Nome",
    "region": "America",
    "city": "Nome",
    "offsetLabel": "UTC-08:00",
    "offsetMinutes": -480
  },
  {
    "value": "America/Sitka",
    "region": "America",
    "city": "Sitka",
    "offsetLabel": "UTC-08:00",
    "offsetMinutes": -480
  },
  {
    "value": "America/Yakutat",
    "region": "America",
    "city": "Yakutat",
    "offsetLabel": "UTC-08:00",
    "offsetMinutes": -480
  },
  {
    "value": "Pacific/Pitcairn",
    "region": "Pacific",
    "city": "Pitcairn",
    "offsetLabel": "UTC-08:00",
    "offsetMinutes": -480
  },
  {
    "value": "America/Creston",
    "region": "America",
    "city": "Creston",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Dawson",
    "region": "America",
    "city": "Dawson",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Dawson_Creek",
    "region": "America",
    "city": "Dawson Creek",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Fort_Nelson",
    "region": "America",
    "city": "Fort Nelson",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Hermosillo",
    "region": "America",
    "city": "Hermosillo",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Los_Angeles",
    "region": "America",
    "city": "Los Angeles",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Mazatlan",
    "region": "America",
    "city": "Mazatlan",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Phoenix",
    "region": "America",
    "city": "Phoenix",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Tijuana",
    "region": "America",
    "city": "Tijuana",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Vancouver",
    "region": "America",
    "city": "Vancouver",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Whitehorse",
    "region": "America",
    "city": "Whitehorse",
    "offsetLabel": "UTC-07:00",
    "offsetMinutes": -420
  },
  {
    "value": "America/Bahia_Banderas",
    "region": "America",
    "city": "Bahia Banderas",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Belize",
    "region": "America",
    "city": "Belize",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Boise",
    "region": "America",
    "city": "Boise",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Cambridge_Bay",
    "region": "America",
    "city": "Cambridge Bay",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Chihuahua",
    "region": "America",
    "city": "Chihuahua",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Ciudad_Juarez",
    "region": "America",
    "city": "Ciudad Juarez",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Costa_Rica",
    "region": "America",
    "city": "Costa Rica",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Denver",
    "region": "America",
    "city": "Denver",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Edmonton",
    "region": "America",
    "city": "Edmonton",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/El_Salvador",
    "region": "America",
    "city": "El Salvador",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Guatemala",
    "region": "America",
    "city": "Guatemala",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Inuvik",
    "region": "America",
    "city": "Inuvik",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Managua",
    "region": "America",
    "city": "Managua",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Merida",
    "region": "America",
    "city": "Merida",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Mexico_City",
    "region": "America",
    "city": "Mexico City",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Monterrey",
    "region": "America",
    "city": "Monterrey",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Regina",
    "region": "America",
    "city": "Regina",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Swift_Current",
    "region": "America",
    "city": "Swift Current",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Tegucigalpa",
    "region": "America",
    "city": "Tegucigalpa",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "Pacific/Easter",
    "region": "Pacific",
    "city": "Easter",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "Pacific/Galapagos",
    "region": "Pacific",
    "city": "Galapagos",
    "offsetLabel": "UTC-06:00",
    "offsetMinutes": -360
  },
  {
    "value": "America/Bogota",
    "region": "America",
    "city": "Bogota",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Cancun",
    "region": "America",
    "city": "Cancun",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Cayman",
    "region": "America",
    "city": "Cayman",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Chicago",
    "region": "America",
    "city": "Chicago",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Coral_Harbour",
    "region": "America",
    "city": "Coral Harbour",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Eirunepe",
    "region": "America",
    "city": "Eirunepe",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Guayaquil",
    "region": "America",
    "city": "Guayaquil",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Indiana/Knox",
    "region": "America",
    "city": "Knox",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Indiana/Tell_City",
    "region": "America",
    "city": "Tell City",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Jamaica",
    "region": "America",
    "city": "Jamaica",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Lima",
    "region": "America",
    "city": "Lima",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Matamoros",
    "region": "America",
    "city": "Matamoros",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Menominee",
    "region": "America",
    "city": "Menominee",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/North_Dakota/Beulah",
    "region": "America",
    "city": "Beulah",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/North_Dakota/Center",
    "region": "America",
    "city": "Center",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/North_Dakota/New_Salem",
    "region": "America",
    "city": "New Salem",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Ojinaga",
    "region": "America",
    "city": "Ojinaga",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Panama",
    "region": "America",
    "city": "Panama",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Rankin_Inlet",
    "region": "America",
    "city": "Rankin Inlet",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Resolute",
    "region": "America",
    "city": "Resolute",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Rio_Branco",
    "region": "America",
    "city": "Rio Branco",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Winnipeg",
    "region": "America",
    "city": "Winnipeg",
    "offsetLabel": "UTC-05:00",
    "offsetMinutes": -300
  },
  {
    "value": "America/Anguilla",
    "region": "America",
    "city": "Anguilla",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Antigua",
    "region": "America",
    "city": "Antigua",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Aruba",
    "region": "America",
    "city": "Aruba",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Barbados",
    "region": "America",
    "city": "Barbados",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Blanc-Sablon",
    "region": "America",
    "city": "Blanc-Sablon",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Boa_Vista",
    "region": "America",
    "city": "Boa Vista",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Campo_Grande",
    "region": "America",
    "city": "Campo Grande",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Caracas",
    "region": "America",
    "city": "Caracas",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Cuiaba",
    "region": "America",
    "city": "Cuiaba",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Curacao",
    "region": "America",
    "city": "Curacao",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Detroit",
    "region": "America",
    "city": "Detroit",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Dominica",
    "region": "America",
    "city": "Dominica",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Grand_Turk",
    "region": "America",
    "city": "Grand Turk",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Grenada",
    "region": "America",
    "city": "Grenada",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Guadeloupe",
    "region": "America",
    "city": "Guadeloupe",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Guyana",
    "region": "America",
    "city": "Guyana",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Havana",
    "region": "America",
    "city": "Havana",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Indiana/Marengo",
    "region": "America",
    "city": "Marengo",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Indiana/Petersburg",
    "region": "America",
    "city": "Petersburg",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Indiana/Vevay",
    "region": "America",
    "city": "Vevay",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Indiana/Vincennes",
    "region": "America",
    "city": "Vincennes",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Indiana/Winamac",
    "region": "America",
    "city": "Winamac",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Indianapolis",
    "region": "America",
    "city": "Indianapolis",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Iqaluit",
    "region": "America",
    "city": "Iqaluit",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Kentucky/Monticello",
    "region": "America",
    "city": "Monticello",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Kralendijk",
    "region": "America",
    "city": "Kralendijk",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/La_Paz",
    "region": "America",
    "city": "La Paz",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Louisville",
    "region": "America",
    "city": "Louisville",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Lower_Princes",
    "region": "America",
    "city": "Lower Princes",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Manaus",
    "region": "America",
    "city": "Manaus",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Marigot",
    "region": "America",
    "city": "Marigot",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Martinique",
    "region": "America",
    "city": "Martinique",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Montserrat",
    "region": "America",
    "city": "Montserrat",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Nassau",
    "region": "America",
    "city": "Nassau",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/New_York",
    "region": "America",
    "city": "New York",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Port_of_Spain",
    "region": "America",
    "city": "Port of Spain",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Port-au-Prince",
    "region": "America",
    "city": "Port-au-Prince",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Porto_Velho",
    "region": "America",
    "city": "Porto Velho",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Puerto_Rico",
    "region": "America",
    "city": "Puerto Rico",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Santiago",
    "region": "America",
    "city": "Santiago",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Santo_Domingo",
    "region": "America",
    "city": "Santo Domingo",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/St_Barthelemy",
    "region": "America",
    "city": "St Barthelemy",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/St_Kitts",
    "region": "America",
    "city": "St Kitts",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/St_Lucia",
    "region": "America",
    "city": "St Lucia",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/St_Thomas",
    "region": "America",
    "city": "St Thomas",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/St_Vincent",
    "region": "America",
    "city": "St Vincent",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Toronto",
    "region": "America",
    "city": "Toronto",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Tortola",
    "region": "America",
    "city": "Tortola",
    "offsetLabel": "UTC-04:00",
    "offsetMinutes": -240
  },
  {
    "value": "America/Araguaina",
    "region": "America",
    "city": "Araguaina",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Argentina/La_Rioja",
    "region": "America",
    "city": "La Rioja",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Argentina/Rio_Gallegos",
    "region": "America",
    "city": "Rio Gallegos",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Argentina/Salta",
    "region": "America",
    "city": "Salta",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Argentina/San_Juan",
    "region": "America",
    "city": "San Juan",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Argentina/San_Luis",
    "region": "America",
    "city": "San Luis",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Argentina/Tucuman",
    "region": "America",
    "city": "Tucuman",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Argentina/Ushuaia",
    "region": "America",
    "city": "Ushuaia",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Asuncion",
    "region": "America",
    "city": "Asuncion",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Bahia",
    "region": "America",
    "city": "Bahia",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Belem",
    "region": "America",
    "city": "Belem",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Buenos_Aires",
    "region": "America",
    "city": "Buenos Aires",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Catamarca",
    "region": "America",
    "city": "Catamarca",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Cayenne",
    "region": "America",
    "city": "Cayenne",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Cordoba",
    "region": "America",
    "city": "Cordoba",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Coyhaique",
    "region": "America",
    "city": "Coyhaique",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Fortaleza",
    "region": "America",
    "city": "Fortaleza",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Glace_Bay",
    "region": "America",
    "city": "Glace Bay",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Goose_Bay",
    "region": "America",
    "city": "Goose Bay",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Halifax",
    "region": "America",
    "city": "Halifax",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Jujuy",
    "region": "America",
    "city": "Jujuy",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Maceio",
    "region": "America",
    "city": "Maceio",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Mendoza",
    "region": "America",
    "city": "Mendoza",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Moncton",
    "region": "America",
    "city": "Moncton",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Montevideo",
    "region": "America",
    "city": "Montevideo",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Paramaribo",
    "region": "America",
    "city": "Paramaribo",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Punta_Arenas",
    "region": "America",
    "city": "Punta Arenas",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Recife",
    "region": "America",
    "city": "Recife",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Santarem",
    "region": "America",
    "city": "Santarem",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Sao_Paulo",
    "region": "America",
    "city": "Sao Paulo",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/Thule",
    "region": "America",
    "city": "Thule",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "Antarctica/Palmer",
    "region": "Antarctica",
    "city": "Palmer",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "Antarctica/Rothera",
    "region": "Antarctica",
    "city": "Rothera",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "Atlantic/Bermuda",
    "region": "Atlantic",
    "city": "Bermuda",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "Atlantic/Stanley",
    "region": "Atlantic",
    "city": "Stanley",
    "offsetLabel": "UTC-03:00",
    "offsetMinutes": -180
  },
  {
    "value": "America/St_Johns",
    "region": "America",
    "city": "St Johns",
    "offsetLabel": "UTC-02:30",
    "offsetMinutes": -150
  },
  {
    "value": "America/Miquelon",
    "region": "America",
    "city": "Miquelon",
    "offsetLabel": "UTC-02:00",
    "offsetMinutes": -120
  },
  {
    "value": "America/Noronha",
    "region": "America",
    "city": "Noronha",
    "offsetLabel": "UTC-02:00",
    "offsetMinutes": -120
  },
  {
    "value": "Atlantic/South_Georgia",
    "region": "Atlantic",
    "city": "South Georgia",
    "offsetLabel": "UTC-02:00",
    "offsetMinutes": -120
  },
  {
    "value": "America/Godthab",
    "region": "America",
    "city": "Godthab",
    "offsetLabel": "UTC-01:00",
    "offsetMinutes": -60
  },
  {
    "value": "America/Scoresbysund",
    "region": "America",
    "city": "Scoresbysund",
    "offsetLabel": "UTC-01:00",
    "offsetMinutes": -60
  },
  {
    "value": "Atlantic/Cape_Verde",
    "region": "Atlantic",
    "city": "Cape Verde",
    "offsetLabel": "UTC-01:00",
    "offsetMinutes": -60
  },
  {
    "value": "Africa/Abidjan",
    "region": "Africa",
    "city": "Abidjan",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Accra",
    "region": "Africa",
    "city": "Accra",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Bamako",
    "region": "Africa",
    "city": "Bamako",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Banjul",
    "region": "Africa",
    "city": "Banjul",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Bissau",
    "region": "Africa",
    "city": "Bissau",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Conakry",
    "region": "Africa",
    "city": "Conakry",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Dakar",
    "region": "Africa",
    "city": "Dakar",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Freetown",
    "region": "Africa",
    "city": "Freetown",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Lome",
    "region": "Africa",
    "city": "Lome",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Monrovia",
    "region": "Africa",
    "city": "Monrovia",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Nouakchott",
    "region": "Africa",
    "city": "Nouakchott",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Ouagadougou",
    "region": "Africa",
    "city": "Ouagadougou",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Sao_Tome",
    "region": "Africa",
    "city": "Sao Tome",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "America/Danmarkshavn",
    "region": "America",
    "city": "Danmarkshavn",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Atlantic/Azores",
    "region": "Atlantic",
    "city": "Azores",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Atlantic/Reykjavik",
    "region": "Atlantic",
    "city": "Reykjavik",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Atlantic/St_Helena",
    "region": "Atlantic",
    "city": "St Helena",
    "offsetLabel": "UTC+00:00",
    "offsetMinutes": 0
  },
  {
    "value": "Africa/Algiers",
    "region": "Africa",
    "city": "Algiers",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Bangui",
    "region": "Africa",
    "city": "Bangui",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Brazzaville",
    "region": "Africa",
    "city": "Brazzaville",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Casablanca",
    "region": "Africa",
    "city": "Casablanca",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Douala",
    "region": "Africa",
    "city": "Douala",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/El_Aaiun",
    "region": "Africa",
    "city": "El Aaiun",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Kinshasa",
    "region": "Africa",
    "city": "Kinshasa",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Lagos",
    "region": "Africa",
    "city": "Lagos",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Libreville",
    "region": "Africa",
    "city": "Libreville",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Luanda",
    "region": "Africa",
    "city": "Luanda",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Malabo",
    "region": "Africa",
    "city": "Malabo",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Ndjamena",
    "region": "Africa",
    "city": "Ndjamena",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Niamey",
    "region": "Africa",
    "city": "Niamey",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Porto-Novo",
    "region": "Africa",
    "city": "Porto-Novo",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Tunis",
    "region": "Africa",
    "city": "Tunis",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Atlantic/Canary",
    "region": "Atlantic",
    "city": "Canary",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Atlantic/Faeroe",
    "region": "Atlantic",
    "city": "Faroe",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Atlantic/Madeira",
    "region": "Atlantic",
    "city": "Madeira",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Europe/Dublin",
    "region": "Europe",
    "city": "Dublin",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Europe/Guernsey",
    "region": "Europe",
    "city": "Guernsey",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Europe/Isle_of_Man",
    "region": "Europe",
    "city": "Isle of Man",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Europe/Jersey",
    "region": "Europe",
    "city": "Jersey",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Europe/Lisbon",
    "region": "Europe",
    "city": "Lisbon",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Europe/London",
    "region": "Europe",
    "city": "London",
    "offsetLabel": "UTC+01:00",
    "offsetMinutes": 60
  },
  {
    "value": "Africa/Blantyre",
    "region": "Africa",
    "city": "Blantyre",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Bujumbura",
    "region": "Africa",
    "city": "Bujumbura",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Ceuta",
    "region": "Africa",
    "city": "Ceuta",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Gaborone",
    "region": "Africa",
    "city": "Gaborone",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Harare",
    "region": "Africa",
    "city": "Harare",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Johannesburg",
    "region": "Africa",
    "city": "Johannesburg",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Juba",
    "region": "Africa",
    "city": "Juba",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Khartoum",
    "region": "Africa",
    "city": "Khartoum",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Kigali",
    "region": "Africa",
    "city": "Kigali",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Lubumbashi",
    "region": "Africa",
    "city": "Lubumbashi",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Lusaka",
    "region": "Africa",
    "city": "Lusaka",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Maputo",
    "region": "Africa",
    "city": "Maputo",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Maseru",
    "region": "Africa",
    "city": "Maseru",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Mbabane",
    "region": "Africa",
    "city": "Mbabane",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Tripoli",
    "region": "Africa",
    "city": "Tripoli",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Windhoek",
    "region": "Africa",
    "city": "Windhoek",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Antarctica/Troll",
    "region": "Antarctica",
    "city": "Troll",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Arctic/Longyearbyen",
    "region": "Arctic",
    "city": "Longyearbyen",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Amsterdam",
    "region": "Europe",
    "city": "Amsterdam",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Andorra",
    "region": "Europe",
    "city": "Andorra",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Belgrade",
    "region": "Europe",
    "city": "Belgrade",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Berlin",
    "region": "Europe",
    "city": "Berlin",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Bratislava",
    "region": "Europe",
    "city": "Bratislava",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Brussels",
    "region": "Europe",
    "city": "Brussels",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Budapest",
    "region": "Europe",
    "city": "Budapest",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Busingen",
    "region": "Europe",
    "city": "Busingen",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Copenhagen",
    "region": "Europe",
    "city": "Copenhagen",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Gibraltar",
    "region": "Europe",
    "city": "Gibraltar",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Kaliningrad",
    "region": "Europe",
    "city": "Kaliningrad",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Ljubljana",
    "region": "Europe",
    "city": "Ljubljana",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Luxembourg",
    "region": "Europe",
    "city": "Luxembourg",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Madrid",
    "region": "Europe",
    "city": "Madrid",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Malta",
    "region": "Europe",
    "city": "Malta",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Monaco",
    "region": "Europe",
    "city": "Monaco",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Oslo",
    "region": "Europe",
    "city": "Oslo",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Paris",
    "region": "Europe",
    "city": "Paris",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Podgorica",
    "region": "Europe",
    "city": "Podgorica",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Prague",
    "region": "Europe",
    "city": "Prague",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Rome",
    "region": "Europe",
    "city": "Rome",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/San_Marino",
    "region": "Europe",
    "city": "San Marino",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Sarajevo",
    "region": "Europe",
    "city": "Sarajevo",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Skopje",
    "region": "Europe",
    "city": "Skopje",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Stockholm",
    "region": "Europe",
    "city": "Stockholm",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Tirane",
    "region": "Europe",
    "city": "Tirane",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Vaduz",
    "region": "Europe",
    "city": "Vaduz",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Vatican",
    "region": "Europe",
    "city": "Vatican",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Vienna",
    "region": "Europe",
    "city": "Vienna",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Warsaw",
    "region": "Europe",
    "city": "Warsaw",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Zagreb",
    "region": "Europe",
    "city": "Zagreb",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Europe/Zurich",
    "region": "Europe",
    "city": "Zurich",
    "offsetLabel": "UTC+02:00",
    "offsetMinutes": 120
  },
  {
    "value": "Africa/Addis_Ababa",
    "region": "Africa",
    "city": "Addis Ababa",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Africa/Asmera",
    "region": "Africa",
    "city": "Asmara",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Africa/Cairo",
    "region": "Africa",
    "city": "Cairo",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Africa/Dar_es_Salaam",
    "region": "Africa",
    "city": "Dar es Salaam",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Africa/Djibouti",
    "region": "Africa",
    "city": "Djibouti",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Africa/Kampala",
    "region": "Africa",
    "city": "Kampala",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Africa/Mogadishu",
    "region": "Africa",
    "city": "Mogadishu",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Africa/Nairobi",
    "region": "Africa",
    "city": "Nairobi",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Antarctica/Syowa",
    "region": "Antarctica",
    "city": "Syowa",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Aden",
    "region": "Asia",
    "city": "Aden",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Amman",
    "region": "Asia",
    "city": "Amman",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Baghdad",
    "region": "Asia",
    "city": "Baghdad",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Bahrain",
    "region": "Asia",
    "city": "Bahrain",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Beirut",
    "region": "Asia",
    "city": "Beirut",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Damascus",
    "region": "Asia",
    "city": "Damascus",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Famagusta",
    "region": "Asia",
    "city": "Famagusta",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Gaza",
    "region": "Asia",
    "city": "Gaza",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Hebron",
    "region": "Asia",
    "city": "Hebron",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Jerusalem",
    "region": "Asia",
    "city": "Jerusalem",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Kuwait",
    "region": "Asia",
    "city": "Kuwait",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Nicosia",
    "region": "Asia",
    "city": "Nicosia",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Qatar",
    "region": "Asia",
    "city": "Qatar",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Riyadh",
    "region": "Asia",
    "city": "Riyadh",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Athens",
    "region": "Europe",
    "city": "Athens",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Bucharest",
    "region": "Europe",
    "city": "Bucharest",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Chisinau",
    "region": "Europe",
    "city": "Chisinau",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Helsinki",
    "region": "Europe",
    "city": "Helsinki",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Istanbul",
    "region": "Europe",
    "city": "Istanbul",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Kiev",
    "region": "Europe",
    "city": "Kyiv",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Kirov",
    "region": "Europe",
    "city": "Kirov",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Mariehamn",
    "region": "Europe",
    "city": "Mariehamn",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Minsk",
    "region": "Europe",
    "city": "Minsk",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Moscow",
    "region": "Europe",
    "city": "Moscow",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Riga",
    "region": "Europe",
    "city": "Riga",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Simferopol",
    "region": "Europe",
    "city": "Simferopol",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Sofia",
    "region": "Europe",
    "city": "Sofia",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Tallinn",
    "region": "Europe",
    "city": "Tallinn",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Vilnius",
    "region": "Europe",
    "city": "Vilnius",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Europe/Volgograd",
    "region": "Europe",
    "city": "Volgograd",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Indian/Antananarivo",
    "region": "Indian",
    "city": "Antananarivo",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Indian/Comoro",
    "region": "Indian",
    "city": "Comoro",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Indian/Mayotte",
    "region": "Indian",
    "city": "Mayotte",
    "offsetLabel": "UTC+03:00",
    "offsetMinutes": 180
  },
  {
    "value": "Asia/Tehran",
    "region": "Asia",
    "city": "Tehran",
    "offsetLabel": "UTC+03:30",
    "offsetMinutes": 210
  },
  {
    "value": "Asia/Baku",
    "region": "Asia",
    "city": "Baku",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Asia/Dubai",
    "region": "Asia",
    "city": "Dubai",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Asia/Muscat",
    "region": "Asia",
    "city": "Muscat",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Asia/Tbilisi",
    "region": "Asia",
    "city": "Tbilisi",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Asia/Yerevan",
    "region": "Asia",
    "city": "Yerevan",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Europe/Astrakhan",
    "region": "Europe",
    "city": "Astrakhan",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Europe/Samara",
    "region": "Europe",
    "city": "Samara",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Europe/Saratov",
    "region": "Europe",
    "city": "Saratov",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Europe/Ulyanovsk",
    "region": "Europe",
    "city": "Ulyanovsk",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Indian/Mahe",
    "region": "Indian",
    "city": "Mahe",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Indian/Mauritius",
    "region": "Indian",
    "city": "Mauritius",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Indian/Reunion",
    "region": "Indian",
    "city": "Reunion",
    "offsetLabel": "UTC+04:00",
    "offsetMinutes": 240
  },
  {
    "value": "Asia/Kabul",
    "region": "Asia",
    "city": "Kabul",
    "offsetLabel": "UTC+04:30",
    "offsetMinutes": 270
  },
  {
    "value": "Antarctica/Mawson",
    "region": "Antarctica",
    "city": "Mawson",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Antarctica/Vostok",
    "region": "Antarctica",
    "city": "Vostok",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Almaty",
    "region": "Asia",
    "city": "Almaty",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Aqtau",
    "region": "Asia",
    "city": "Aqtau",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Aqtobe",
    "region": "Asia",
    "city": "Aqtobe",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Ashgabat",
    "region": "Asia",
    "city": "Ashgabat",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Atyrau",
    "region": "Asia",
    "city": "Atyrau",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Dushanbe",
    "region": "Asia",
    "city": "Dushanbe",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Karachi",
    "region": "Asia",
    "city": "Karachi",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Oral",
    "region": "Asia",
    "city": "Oral",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Qostanay",
    "region": "Asia",
    "city": "Qostanay",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Qyzylorda",
    "region": "Asia",
    "city": "Qyzylorda",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Samarkand",
    "region": "Asia",
    "city": "Samarkand",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Tashkent",
    "region": "Asia",
    "city": "Tashkent",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Yekaterinburg",
    "region": "Asia",
    "city": "Yekaterinburg",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Indian/Kerguelen",
    "region": "Indian",
    "city": "Kerguelen",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Indian/Maldives",
    "region": "Indian",
    "city": "Maldives",
    "offsetLabel": "UTC+05:00",
    "offsetMinutes": 300
  },
  {
    "value": "Asia/Calcutta",
    "region": "Asia",
    "city": "Kolkata",
    "offsetLabel": "UTC+05:30",
    "offsetMinutes": 330
  },
  {
    "value": "Asia/Colombo",
    "region": "Asia",
    "city": "Colombo",
    "offsetLabel": "UTC+05:30",
    "offsetMinutes": 330
  },
  {
    "value": "Asia/Katmandu",
    "region": "Asia",
    "city": "Kathmandu",
    "offsetLabel": "UTC+05:45",
    "offsetMinutes": 345
  },
  {
    "value": "Asia/Bishkek",
    "region": "Asia",
    "city": "Bishkek",
    "offsetLabel": "UTC+06:00",
    "offsetMinutes": 360
  },
  {
    "value": "Asia/Dhaka",
    "region": "Asia",
    "city": "Dhaka",
    "offsetLabel": "UTC+06:00",
    "offsetMinutes": 360
  },
  {
    "value": "Asia/Omsk",
    "region": "Asia",
    "city": "Omsk",
    "offsetLabel": "UTC+06:00",
    "offsetMinutes": 360
  },
  {
    "value": "Asia/Thimphu",
    "region": "Asia",
    "city": "Thimphu",
    "offsetLabel": "UTC+06:00",
    "offsetMinutes": 360
  },
  {
    "value": "Asia/Urumqi",
    "region": "Asia",
    "city": "Urumqi",
    "offsetLabel": "UTC+06:00",
    "offsetMinutes": 360
  },
  {
    "value": "Indian/Chagos",
    "region": "Indian",
    "city": "Chagos",
    "offsetLabel": "UTC+06:00",
    "offsetMinutes": 360
  },
  {
    "value": "Asia/Rangoon",
    "region": "Asia",
    "city": "Yangon",
    "offsetLabel": "UTC+06:30",
    "offsetMinutes": 390
  },
  {
    "value": "Indian/Cocos",
    "region": "Indian",
    "city": "Cocos",
    "offsetLabel": "UTC+06:30",
    "offsetMinutes": 390
  },
  {
    "value": "Antarctica/Davis",
    "region": "Antarctica",
    "city": "Davis",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Bangkok",
    "region": "Asia",
    "city": "Bangkok",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Barnaul",
    "region": "Asia",
    "city": "Barnaul",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Hovd",
    "region": "Asia",
    "city": "Hovd",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Jakarta",
    "region": "Asia",
    "city": "Jakarta",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Krasnoyarsk",
    "region": "Asia",
    "city": "Krasnoyarsk",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Novokuznetsk",
    "region": "Asia",
    "city": "Novokuznetsk",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Novosibirsk",
    "region": "Asia",
    "city": "Novosibirsk",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Phnom_Penh",
    "region": "Asia",
    "city": "Phnom Penh",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Pontianak",
    "region": "Asia",
    "city": "Pontianak",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Saigon",
    "region": "Asia",
    "city": "Ho Chi Minh City",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Tomsk",
    "region": "Asia",
    "city": "Tomsk",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Asia/Vientiane",
    "region": "Asia",
    "city": "Vientiane",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Indian/Christmas",
    "region": "Indian",
    "city": "Christmas",
    "offsetLabel": "UTC+07:00",
    "offsetMinutes": 420
  },
  {
    "value": "Antarctica/Casey",
    "region": "Antarctica",
    "city": "Casey",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Brunei",
    "region": "Asia",
    "city": "Brunei",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Hong_Kong",
    "region": "Asia",
    "city": "Hong Kong",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Irkutsk",
    "region": "Asia",
    "city": "Irkutsk",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Kuala_Lumpur",
    "region": "Asia",
    "city": "Kuala Lumpur",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Kuching",
    "region": "Asia",
    "city": "Kuching",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Macau",
    "region": "Asia",
    "city": "Macau",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Makassar",
    "region": "Asia",
    "city": "Makassar",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Manila",
    "region": "Asia",
    "city": "Manila",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Shanghai",
    "region": "Asia",
    "city": "Shanghai",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Singapore",
    "region": "Asia",
    "city": "Singapore",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Taipei",
    "region": "Asia",
    "city": "Taipei",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Asia/Ulaanbaatar",
    "region": "Asia",
    "city": "Ulaanbaatar",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Australia/Perth",
    "region": "Australia",
    "city": "Perth",
    "offsetLabel": "UTC+08:00",
    "offsetMinutes": 480
  },
  {
    "value": "Australia/Eucla",
    "region": "Australia",
    "city": "Eucla",
    "offsetLabel": "UTC+08:45",
    "offsetMinutes": 525
  },
  {
    "value": "Asia/Chita",
    "region": "Asia",
    "city": "Chita",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Asia/Dili",
    "region": "Asia",
    "city": "Dili",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Asia/Jayapura",
    "region": "Asia",
    "city": "Jayapura",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Asia/Khandyga",
    "region": "Asia",
    "city": "Khandyga",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Asia/Pyongyang",
    "region": "Asia",
    "city": "Pyongyang",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Asia/Seoul",
    "region": "Asia",
    "city": "Seoul",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Asia/Tokyo",
    "region": "Asia",
    "city": "Tokyo",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Asia/Yakutsk",
    "region": "Asia",
    "city": "Yakutsk",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Pacific/Palau",
    "region": "Pacific",
    "city": "Palau",
    "offsetLabel": "UTC+09:00",
    "offsetMinutes": 540
  },
  {
    "value": "Australia/Adelaide",
    "region": "Australia",
    "city": "Adelaide",
    "offsetLabel": "UTC+09:30",
    "offsetMinutes": 570
  },
  {
    "value": "Australia/Broken_Hill",
    "region": "Australia",
    "city": "Broken Hill",
    "offsetLabel": "UTC+09:30",
    "offsetMinutes": 570
  },
  {
    "value": "Australia/Darwin",
    "region": "Australia",
    "city": "Darwin",
    "offsetLabel": "UTC+09:30",
    "offsetMinutes": 570
  },
  {
    "value": "Antarctica/DumontDUrville",
    "region": "Antarctica",
    "city": "DumontDUrville",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Antarctica/Macquarie",
    "region": "Antarctica",
    "city": "Macquarie",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Asia/Ust-Nera",
    "region": "Asia",
    "city": "Ust-Nera",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Asia/Vladivostok",
    "region": "Asia",
    "city": "Vladivostok",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Australia/Brisbane",
    "region": "Australia",
    "city": "Brisbane",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Australia/Hobart",
    "region": "Australia",
    "city": "Hobart",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Australia/Lindeman",
    "region": "Australia",
    "city": "Lindeman",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Australia/Melbourne",
    "region": "Australia",
    "city": "Melbourne",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Australia/Sydney",
    "region": "Australia",
    "city": "Sydney",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Pacific/Guam",
    "region": "Pacific",
    "city": "Guam",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Pacific/Port_Moresby",
    "region": "Pacific",
    "city": "Port Moresby",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Pacific/Saipan",
    "region": "Pacific",
    "city": "Saipan",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Pacific/Truk",
    "region": "Pacific",
    "city": "Truk",
    "offsetLabel": "UTC+10:00",
    "offsetMinutes": 600
  },
  {
    "value": "Australia/Lord_Howe",
    "region": "Australia",
    "city": "Lord Howe",
    "offsetLabel": "UTC+10:30",
    "offsetMinutes": 630
  },
  {
    "value": "Asia/Magadan",
    "region": "Asia",
    "city": "Magadan",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Asia/Sakhalin",
    "region": "Asia",
    "city": "Sakhalin",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Asia/Srednekolymsk",
    "region": "Asia",
    "city": "Srednekolymsk",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Pacific/Bougainville",
    "region": "Pacific",
    "city": "Bougainville",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Pacific/Efate",
    "region": "Pacific",
    "city": "Efate",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Pacific/Guadalcanal",
    "region": "Pacific",
    "city": "Guadalcanal",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Pacific/Kosrae",
    "region": "Pacific",
    "city": "Kosrae",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Pacific/Norfolk",
    "region": "Pacific",
    "city": "Norfolk",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Pacific/Noumea",
    "region": "Pacific",
    "city": "Noumea",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Pacific/Ponape",
    "region": "Pacific",
    "city": "Ponape",
    "offsetLabel": "UTC+11:00",
    "offsetMinutes": 660
  },
  {
    "value": "Antarctica/McMurdo",
    "region": "Antarctica",
    "city": "McMurdo",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Asia/Anadyr",
    "region": "Asia",
    "city": "Anadyr",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Asia/Kamchatka",
    "region": "Asia",
    "city": "Kamchatka",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Auckland",
    "region": "Pacific",
    "city": "Auckland",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Fiji",
    "region": "Pacific",
    "city": "Fiji",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Funafuti",
    "region": "Pacific",
    "city": "Funafuti",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Kwajalein",
    "region": "Pacific",
    "city": "Kwajalein",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Majuro",
    "region": "Pacific",
    "city": "Majuro",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Nauru",
    "region": "Pacific",
    "city": "Nauru",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Tarawa",
    "region": "Pacific",
    "city": "Tarawa",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Wake",
    "region": "Pacific",
    "city": "Wake",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Wallis",
    "region": "Pacific",
    "city": "Wallis",
    "offsetLabel": "UTC+12:00",
    "offsetMinutes": 720
  },
  {
    "value": "Pacific/Chatham",
    "region": "Pacific",
    "city": "Chatham",
    "offsetLabel": "UTC+12:45",
    "offsetMinutes": 765
  },
  {
    "value": "Pacific/Apia",
    "region": "Pacific",
    "city": "Apia",
    "offsetLabel": "UTC+13:00",
    "offsetMinutes": 780
  },
  {
    "value": "Pacific/Enderbury",
    "region": "Pacific",
    "city": "Enderbury",
    "offsetLabel": "UTC+13:00",
    "offsetMinutes": 780
  },
  {
    "value": "Pacific/Fakaofo",
    "region": "Pacific",
    "city": "Fakaofo",
    "offsetLabel": "UTC+13:00",
    "offsetMinutes": 780
  },
  {
    "value": "Pacific/Tongatapu",
    "region": "Pacific",
    "city": "Tongatapu",
    "offsetLabel": "UTC+13:00",
    "offsetMinutes": 780
  },
  {
    "value": "Pacific/Kiritimati",
    "region": "Pacific",
    "city": "Kiritimati",
    "offsetLabel": "UTC+14:00",
    "offsetMinutes": 840
  }
];

const TZ_BY_VALUE: Record<string, Timezone> = Object.fromEntries(
  TIMEZONES.map((t) => [t.value, t]),
);

export function timezoneByValue(value: string): Timezone | undefined {
  return TZ_BY_VALUE[value];
}
