import { writeFileSync } from "node:fs";

const OUT_DIR = new URL("../src/lib", import.meta.url).pathname;

// ─── Currencies (ISO 4217, via ICU) ──────────────────────────────────────────
const currencyCodes = Intl.supportedValuesOf("currency");
const curName = new Intl.DisplayNames(["en"], { type: "currency" });
const regionName = new Intl.DisplayNames(["en"], { type: "region" });

function symbolFor(code) {
  try {
    const parts = new Intl.NumberFormat("en", {
      style: "currency",
      currency: code,
      currencyDisplay: "narrowSymbol",
      maximumFractionDigits: 0,
    }).formatToParts(0);
    const sym = parts.find((p) => p.type === "currency")?.value;
    return sym && sym !== code ? sym : "";
  } catch {
    return "";
  }
}

// A currency code is usually <ISO-3166 alpha-2><letter>, e.g. USD -> US.
// Only assign a flag when that 2-letter prefix is a real region. EUR is the
// notable supranational exception that flag-icons still ships ("eu").
function flagFor(code) {
  if (code === "EUR") return "eu";
  const cc = code.slice(0, 2).toUpperCase();
  if (cc.startsWith("X")) return ""; // XOF, XAF, XDR… supranational, no flag
  const name = regionName.of(cc);
  return name && name !== cc ? cc.toLowerCase() : "";
}

const currencies = currencyCodes
  .map((code) => ({
    code,
    name: curName.of(code) ?? code,
    symbol: symbolFor(code),
    flag: flagFor(code),
  }))
  // Drop entries with no human name (a few ICU test codes) and dedupe.
  .filter((c) => c.name && c.name !== c.code)
  .sort((a, b) => a.code.localeCompare(b.code));

// ─── Timezones (IANA, via ICU) ───────────────────────────────────────────────
const tzList = Intl.supportedValuesOf("timeZone");
const now = new Date();

// ICU still reports some legacy city names; show the modern spelling.
const CITY_FIXUPS = {
  Calcutta: "Kolkata",
  Rangoon: "Yangon",
  Saigon: "Ho Chi Minh City",
  Katmandu: "Kathmandu",
  Asmera: "Asmara",
  Faeroe: "Faroe",
  Kiev: "Kyiv",
  Ulan_Bator: "Ulaanbaatar",
};

function offsetInfo(tz) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    timeZoneName: "shortOffset",
  }).formatToParts(now);
  const raw = parts.find((p) => p.type === "timeZoneName")?.value ?? "GMT";
  // raw like "GMT+9", "GMT-5:30", "GMT". Normalize to "UTC+09:00".
  const m = raw.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);
  let minutes = 0;
  let label = "UTC";
  if (m) {
    const sign = m[1] === "-" ? -1 : 1;
    const h = parseInt(m[2], 10);
    const mm = m[3] ? parseInt(m[3], 10) : 0;
    minutes = sign * (h * 60 + mm);
    const hh = String(h).padStart(2, "0");
    label = `UTC${m[1]}${hh}:${String(mm).padStart(2, "0")}`;
  }
  return { minutes, label };
}

const timezones = tzList
  .map((value) => {
    const [region, ...rest] = value.split("/");
    const lastSeg = rest.length ? rest[rest.length - 1] : value;
    const city = (CITY_FIXUPS[lastSeg] ?? lastSeg).replace(/_/g, " ");
    const { minutes, label } = offsetInfo(value);
    return { value, region, city, offsetLabel: label, offsetMinutes: minutes };
  })
  .sort((a, b) => a.offsetMinutes - b.offsetMinutes || a.value.localeCompare(b.value));

// ─── Emit ────────────────────────────────────────────────────────────────────
const header = (extra) =>
  `// AUTO-GENERATED by scripts/gen-lists.mjs from the runtime Intl/ICU data.\n// Do not edit by hand — re-run the generator to refresh.${extra ? "\n" + extra : ""}\n\n`;

const currencyFile =
  header(
    "// Offset/flag notes: `flag` is a best-effort ISO-3166 mapping (empty when a\n// currency has no single country, e.g. XOF). `symbol` falls back to '' when ICU\n// has no narrow symbol — render the code in that case.",
  ) +
  `export type Currency = { code: string; name: string; symbol: string; flag: string };\n\n` +
  `export const CURRENCIES: Currency[] = ${JSON.stringify(currencies, null, 2)};\n\n` +
  `const BY_CODE: Record<string, Currency> = Object.fromEntries(\n  CURRENCIES.map((c) => [c.code, c]),\n);\n\n` +
  `export function currencyByCode(code: string): Currency | undefined {\n  return BY_CODE[code];\n}\n`;

const tzFile =
  header(
    "// `offsetLabel` is a snapshot from generation time; the stored IANA `value` is\n// what's authoritative and stays DST-correct at runtime.",
  ) +
  `export type Timezone = {\n  value: string;\n  region: string;\n  city: string;\n  offsetLabel: string;\n  offsetMinutes: number;\n};\n\n` +
  `export const TIMEZONES: Timezone[] = ${JSON.stringify(timezones, null, 2)};\n\n` +
  `const TZ_BY_VALUE: Record<string, Timezone> = Object.fromEntries(\n  TIMEZONES.map((t) => [t.value, t]),\n);\n\n` +
  `export function timezoneByValue(value: string): Timezone | undefined {\n  return TZ_BY_VALUE[value];\n}\n`;

writeFileSync(`${OUT_DIR}/currencies.ts`, currencyFile);
writeFileSync(`${OUT_DIR}/timezones.ts`, tzFile);

console.log(`currencies: ${currencies.length}, timezones: ${timezones.length}`);
console.log("sample currency:", JSON.stringify(currencies.find((c) => c.code === "SGD")));
console.log("sample currency (no flag):", JSON.stringify(currencies.find((c) => c.code === "XOF")));
console.log("sample tz:", JSON.stringify(timezones.find((t) => t.value === "Asia/Tokyo")));
console.log("sample tz (half-hr):", JSON.stringify(timezones.find((t) => t.value === "Asia/Kolkata")));
