/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step1'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products_/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders_/index'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts_/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers_/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products_/new'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders_/new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders_/$orderId'
import { Route as AdminDiscountsNewRouteImport } from './routes/admin/discounts_/new'
import { Route as AdminDiscountsDiscountIdRouteImport } from './routes/admin/discounts_/$discountId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers_/$customerId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step3',
  path: '/step3',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step1',
  path: '/step1',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products_/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders_/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts_/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers_/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsNewRoute = AdminDiscountsNewRouteImport.update({
  id: '/discounts_/new',
  path: '/discounts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsDiscountIdRoute =
  AdminDiscountsDiscountIdRouteImport.update({
    id: '/discounts_/$discountId',
    path: '/discounts/$discountId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers_/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/admin/customers_/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/discounts_/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts_/new': typeof AdminDiscountsNewRoute
  '/admin/orders_/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders_/new': typeof AdminOrdersNewRoute
  '/admin/products_/new': typeof AdminProductsNewRoute
  '/admin/customers_/': typeof AdminCustomersIndexRoute
  '/admin/discounts_/': typeof AdminDiscountsIndexRoute
  '/admin/orders_/': typeof AdminOrdersIndexRoute
  '/admin/products_/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/shipping'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/admin/customers/$customerId'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/products/new'
    | '/admin/customers/'
    | '/admin/discounts/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/shipping'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/admin/customers/$customerId'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/products/new'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/shipping'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/admin/customers_/$customerId'
    | '/admin/discounts_/$discountId'
    | '/admin/discounts_/new'
    | '/admin/orders_/$orderId'
    | '/admin/orders_/new'
    | '/admin/products_/new'
    | '/admin/customers_/'
    | '/admin/discounts_/'
    | '/admin/orders_/'
    | '/admin/products_/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step3': {
      id: '/onboarding/step3'
      path: '/step3'
      fullPath: '/onboarding/step3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step2': {
      id: '/onboarding/step2'
      path: '/step2'
      fullPath: '/onboarding/step2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step1': {
      id: '/onboarding/step1'
      path: '/step1'
      fullPath: '/onboarding/step1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products_/': {
      id: '/admin/products_/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders_/': {
      id: '/admin/orders_/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts_/': {
      id: '/admin/discounts_/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers_/': {
      id: '/admin/customers_/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products_/new': {
      id: '/admin/products_/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders_/new': {
      id: '/admin/orders_/new'
      path: '/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders_/$orderId': {
      id: '/admin/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts_/new': {
      id: '/admin/discounts_/new'
      path: '/discounts/new'
      fullPath: '/admin/discounts/new'
      preLoaderRoute: typeof AdminDiscountsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts_/$discountId': {
      id: '/admin/discounts_/$discountId'
      path: '/discounts/$discountId'
      fullPath: '/admin/discounts/$discountId'
      preLoaderRoute: typeof AdminDiscountsDiscountIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers_/$customerId': {
      id: '/admin/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminDiscountsDiscountIdRoute: typeof AdminDiscountsDiscountIdRoute
  AdminDiscountsNewRoute: typeof AdminDiscountsNewRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminDiscountsDiscountIdRoute: AdminDiscountsDiscountIdRoute,
  AdminDiscountsNewRoute: AdminDiscountsNewRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
